# https://docs.travis-ci.com/user/customizing-the-build/

if: tag IS blank
os:
  - linux
language: node_js
node_js:
  - "10"
  - "12"
  - "13"
before_install:
  - node --version
  - npm --version
install:
  - yarn --pure-lockfile
script:
  - npm run dist
