# https://docs.travis-ci.com/user/customizing-the-build/

if: tag IS blank
language: node_js
node_js:
  - "8"
before_install:
  - node --version
  - npm --version
install:
  - npm install
script:
  - npm run dist
